# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 12:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archival_Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_name', models.CharField(blank=True, max_length=200)),
                ('collection_name', models.CharField(blank=True, max_length=200)),
                ('folder_name', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_top', models.CharField(blank=True, max_length=500)),
                ('left_top', models.CharField(blank=True, max_length=500)),
                ('left_bottom', models.CharField(blank=True, max_length=500)),
                ('right_bottom', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Image_Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('cover', models.BooleanField(default=False)),
                ('cover_image', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('image_annotation_coordinates', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.Coordinates')),
            ],
        ),
        migrations.CreateModel(
            name='Image_Annotation_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_annotation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_annotation_tag', to='image_lucida_app.Image_Annotation')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_name', models.CharField(blank=True, max_length=500)),
                ('date_published', models.CharField(blank=True, max_length=500)),
                ('publication_location', models.CharField(blank=True, max_length=500)),
                ('issue_number', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Transform_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_files', to='image_lucida_app.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(blank=True, max_length=500, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Text_Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(blank=True, max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(null=True)),
                ('cover', models.BooleanField(default=False)),
                ('cover_story', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('text_annotation_coordinates', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.Coordinates')),
            ],
        ),
        migrations.CreateModel(
            name='Text_Annotation_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_annotation_tag', to='image_lucida_app.Tag')),
                ('text_annotation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_annotation_tag', to='image_lucida_app.Text_Annotation')),
            ],
        ),
        migrations.CreateModel(
            name='Transform_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transform_file_name', models.CharField(blank=True, max_length=200)),
                ('transform_file', models.FileField(upload_to='transform-files/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('page_number', models.IntegerField(null=True)),
                ('archival_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.Archival_Source')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.Issue')),
                ('transform_file_coordinates', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.Coordinates')),
            ],
        ),
        migrations.CreateModel(
            name='Upload_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file_name', models.CharField(blank=True, max_length=200)),
                ('upload_file', models.FileField(upload_to='upload-files/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('upload_file_coordinates', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.Coordinates')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transform_file',
            name='upload_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.Upload_File'),
        ),
        migrations.AddField(
            model_name='text_annotation',
            name='transform_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.Transform_File'),
        ),
        migrations.AddField(
            model_name='project_transform_file',
            name='transform_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_files', to='image_lucida_app.Transform_File'),
        ),
        migrations.AddField(
            model_name='project',
            name='files',
            field=models.ManyToManyField(through='image_lucida_app.Project_Transform_File', to='image_lucida_app.Transform_File'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image_annotation_tag',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_annotation_tag', to='image_lucida_app.Tag'),
        ),
        migrations.AddField(
            model_name='image_annotation',
            name='transform_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.Transform_File'),
        ),
    ]
