# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=500, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='image_annotation',
            name='tags',
            field=models.ManyToManyField(through='image_lucida_app.Image_Annotation_Tag', to='image_lucida_app.Tag'),
        ),
        migrations.AddField(
            model_name='project',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='text_annotation',
            name='tags',
            field=models.ManyToManyField(through='image_lucida_app.Text_Annotation_Tag', to='image_lucida_app.Tag'),
        ),
        migrations.AddField(
            model_name='project_tag',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_tag', to='image_lucida_app.Project'),
        ),
        migrations.AddField(
            model_name='project_tag',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_tag', to='image_lucida_app.Tag'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.Status'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(through='image_lucida_app.Project_Tag', to='image_lucida_app.Tag'),
        ),
    ]
