# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0002_auto_20170317_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
    ]
