# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0005_auto_20170318_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_file',
            name='transformed',
            field=models.BooleanField(default=False),
        ),
    ]
