# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0006_upload_file_transformed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Upload_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='files',
            new_name='transformed_files',
        ),
        migrations.AlterField(
            model_name='project_transform_file',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_transform_files', to='image_lucida_app.Project'),
        ),
        migrations.AlterField(
            model_name='project_transform_file',
            name='transform_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_transform_files', to='image_lucida_app.Transform_File'),
        ),
        migrations.AddField(
            model_name='project_upload_file',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_upload_files', to='image_lucida_app.Project'),
        ),
        migrations.AddField(
            model_name='project_upload_file',
            name='upload_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_upload_files', to='image_lucida_app.Upload_File'),
        ),
        migrations.AddField(
            model_name='project',
            name='untransformed_files',
            field=models.ManyToManyField(through='image_lucida_app.Project_Upload_File', to='image_lucida_app.Upload_File'),
        ),
    ]
