# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0007_auto_20170319_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinates',
            old_name='left_bottom',
            new_name='bottom_left',
        ),
        migrations.RenameField(
            model_name='coordinates',
            old_name='left_top',
            new_name='bottom_right',
        ),
        migrations.RenameField(
            model_name='coordinates',
            old_name='right_bottom',
            new_name='top_left',
        ),
        migrations.RenameField(
            model_name='coordinates',
            old_name='right_top',
            new_name='top_right',
        ),
    ]
