# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0010_auto_20170322_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transform_file',
            name='transform_file',
            field=models.ImageField(upload_to='transform-files/'),
        ),
    ]
