# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0011_auto_20170323_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transform_file',
            name='page_number',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
