# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0012_auto_20170323_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transform_file',
            name='upload_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.Upload_File'),
        ),
    ]
