# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0015_auto_20170323_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transform_file',
            name='transform_file_coordinates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.Coordinates'),
        ),
        migrations.AlterField(
            model_name='upload_file',
            name='upload_file_coordinates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.Coordinates'),
        ),
    ]
