# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0016_auto_20170323_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_annotation',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='text_annotation',
            name='order',
        ),
        migrations.RemoveField(
            model_name='text_annotation',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='text_annotation',
            name='text_annotation_coordinates',
        ),
        migrations.AddField(
            model_name='text_annotation',
            name='text_annotation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='image_annotation',
            name='image_annotation_coordinates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.Coordinates'),
        ),
    ]
