# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0017_auto_20170323_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archival_source',
            name='archive_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='archival_source',
            name='collection_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='archival_source',
            name='folder_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_name',
            field=models.TextField(blank=True),
        ),
    ]
