# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0019_auto_20170323_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='text_annotation',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
