# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0020_text_annotation_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_annotation',
            name='image_annotation_file_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='image_annotation',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
