# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import image_lucida_app.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0021_auto_20170324_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_annotation',
            name='image_annotation_file',
            field=models.ImageField(null=True, upload_to=image_lucida_app.helpers.UniqueFileName('image-annotations/')),
        ),
    ]
