# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0023_image_annotation_image_palette_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_annotation',
            name='image_palette_file_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
