# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0025_auto_20170404_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text_annotation',
            old_name='google_vision_text_annotionat',
            new_name='google_vision_text_annotation',
        ),
    ]
