# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-26 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import image_lucida_app.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0026_auto_20170405_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Folder_Image_Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_image_annotations', to='image_lucida_app.Folder')),
                ('image_annotation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_image_annotations', to='image_lucida_app.Image_Annotation')),
            ],
        ),
        migrations.CreateModel(
            name='Folder_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_tag', to='image_lucida_app.Folder')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_tag', to='image_lucida_app.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Folder_Text_Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_text_annotations', to='image_lucida_app.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='Folder_Transform_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_transform_files', to='image_lucida_app.Folder')),
                ('transform_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_transform_files', to='image_lucida_app.Transform_File')),
            ],
        ),
        migrations.CreateModel(
            name='Folder_Upload_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_upload_files', to='image_lucida_app.Folder')),
                ('upload_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_upload_files', to='image_lucida_app.Upload_File')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Image_Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_image_annotations', to='image_lucida_app.Project')),
                ('image_annotation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_image_annotations', to='image_lucida_app.Image_Annotation')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Text_Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_text_annotations', to='image_lucida_app.Project')),
            ],
        ),
        migrations.AddField(
            model_name='coordinates',
            name='multi_coords',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='text_annotation',
            name='text_annotation_coordinates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.Coordinates'),
        ),
        migrations.AddField(
            model_name='text_annotation',
            name='text_annotation_file',
            field=models.ImageField(blank=True, upload_to=image_lucida_app.helpers.UniqueFileName('text-annotations/')),
        ),
        migrations.AddField(
            model_name='project_text_annotation',
            name='text_annotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_text_annotations', to='image_lucida_app.Text_Annotation'),
        ),
        migrations.AddField(
            model_name='folder_text_annotation',
            name='text_annotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_text_annotations', to='image_lucida_app.Text_Annotation'),
        ),
        migrations.AddField(
            model_name='folder',
            name='image_annotations',
            field=models.ManyToManyField(through='image_lucida_app.Folder_Image_Annotation', to='image_lucida_app.Image_Annotation'),
        ),
        migrations.AddField(
            model_name='folder',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.Project'),
        ),
        migrations.AddField(
            model_name='folder',
            name='tags',
            field=models.ManyToManyField(through='image_lucida_app.Folder_Tag', to='image_lucida_app.Tag'),
        ),
        migrations.AddField(
            model_name='folder',
            name='text_annotations',
            field=models.ManyToManyField(through='image_lucida_app.Folder_Text_Annotation', to='image_lucida_app.Text_Annotation'),
        ),
        migrations.AddField(
            model_name='folder',
            name='transformed_files',
            field=models.ManyToManyField(through='image_lucida_app.Folder_Transform_File', to='image_lucida_app.Transform_File'),
        ),
        migrations.AddField(
            model_name='folder',
            name='untransformed_files',
            field=models.ManyToManyField(through='image_lucida_app.Folder_Upload_File', to='image_lucida_app.Upload_File'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_annotations',
            field=models.ManyToManyField(through='image_lucida_app.Project_Image_Annotation', to='image_lucida_app.Image_Annotation'),
        ),
        migrations.AddField(
            model_name='project',
            name='text_annotations',
            field=models.ManyToManyField(through='image_lucida_app.Project_Text_Annotation', to='image_lucida_app.Text_Annotation'),
        ),
    ]
