# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-28 20:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image_lucida_app', '0027_auto_20170526_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_upload_file',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project_upload_file',
            name='upload_file',
        ),
        migrations.RemoveField(
            model_name='project',
            name='untransformed_files',
        ),
        migrations.AddField(
            model_name='transform_file',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Project_Upload_File',
        ),
    ]
