# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-06 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0028_auto_20170528_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='transform_file',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
