# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-06 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0029_transform_file_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder_upload_file',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='folder_upload_file',
            name='upload_file',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='untransformed_files',
        ),
        migrations.RemoveField(
            model_name='image_annotation',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='text_annotation',
            name='google_vision_processed',
        ),
        migrations.RemoveField(
            model_name='text_annotation',
            name='tesseract_processed',
        ),
        migrations.AddField(
            model_name='transform_file',
            name='auto_image_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transform_file',
            name='google_vision_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transform_file',
            name='manual_image_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transform_file',
            name='tesseract_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Folder_Upload_File',
        ),
    ]
