# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0030_auto_20170606_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='transform_file',
            name='height',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='transform_file',
            name='width',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
