# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0031_auto_20170611_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transform_File_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transform_file_tag', to='image_lucida_app.Tag')),
                ('transform_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transform_file_tag', to='image_lucida_app.Transform_File')),
            ],
        ),
    ]
