# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0032_transform_file_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='transform_file',
            name='tags',
            field=models.ManyToManyField(through='image_lucida_app.Transform_File_Tag', to='image_lucida_app.Tag'),
        ),
    ]
