# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0033_transform_file_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text_annotation_tag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='text_annotation_tag',
            name='text_annotation',
        ),
        migrations.RemoveField(
            model_name='text_annotation',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Text_Annotation_Tag',
        ),
    ]
