# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-19 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0034_auto_20170617_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_annotation',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='image_annotation',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='image_annotation',
            name='google_vision_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image_annotation',
            name='tesseract_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='text_annotation',
            name='image_annotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.Image_Annotation'),
        ),
        migrations.AddField(
            model_name='transform_file',
            name='cover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transform_file',
            name='cover_image',
            field=models.BooleanField(default=False),
        ),
    ]
