# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-29 18:18
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import image_lucida_app.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0038_auto_20170620_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_name', models.CharField(blank=True, max_length=2000, null=True, unique=True)),
                ('bucket_type', models.CharField(blank=True, max_length=500, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=200, null=True)),
                ('file_item', models.ImageField(upload_to=image_lucida_app.helpers.UniqueFileName('files/'))),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('page_number', models.IntegerField(default=0, null=True)),
                ('assigned', models.BooleanField(default=False)),
                ('tesseract_processed', models.BooleanField(default=False)),
                ('google_vision_processed', models.BooleanField(default=False)),
                ('auto_image_processed', models.BooleanField(default=False)),
                ('manual_image_processed', models.BooleanField(default=False)),
                ('height', models.IntegerField(default=0, null=True)),
                ('width', models.IntegerField(default=0, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_published', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_tag', to='image_lucida_app.File')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.TextField(blank=True, null=True)),
                ('date_published', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('image_file', models.ImageField(null=True, upload_to=image_lucida_app.helpers.UniqueFileName('image-files/'))),
                ('image_file_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('tesseract_processed', models.BooleanField(default=False)),
                ('google_vision_processed', models.BooleanField(default=False)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('file_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.File')),
            ],
        ),
        migrations.CreateModel(
            name='Image_File_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_file_tag', to='image_lucida_app.Image_File')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.TextField(blank=True, null=True, unique=True)),
                ('publication_location', models.CharField(blank=True, max_length=500, null=True)),
                ('bucket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.Bucket')),
            ],
        ),
        migrations.CreateModel(
            name='Text_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('tesseract_text', models.TextField(blank=True, null=True)),
                ('google_vision_text', models.TextField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('tesseract_response', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('google_vision_response', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('file_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.File')),
                ('image_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.Image_File')),
            ],
        ),
        migrations.RemoveField(
            model_name='archival_source',
            name='user',
        ),
        migrations.RemoveField(
            model_name='folder_image_annotation',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='folder_image_annotation',
            name='image_annotation',
        ),
        migrations.RemoveField(
            model_name='folder_tag',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='folder_tag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='folder_text_annotation',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='folder_text_annotation',
            name='text_annotation',
        ),
        migrations.RemoveField(
            model_name='folder_transform_file',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='folder_transform_file',
            name='transform_file',
        ),
        migrations.RemoveField(
            model_name='image_annotation',
            name='image_annotation_coordinates',
        ),
        migrations.RemoveField(
            model_name='image_annotation',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='image_annotation',
            name='transform_file',
        ),
        migrations.RemoveField(
            model_name='image_annotation_tag',
            name='image_annotation',
        ),
        migrations.RemoveField(
            model_name='image_annotation_tag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project_image_annotation',
            name='Project',
        ),
        migrations.RemoveField(
            model_name='project_image_annotation',
            name='image_annotation',
        ),
        migrations.RemoveField(
            model_name='project_tag',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project_tag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='project_text_annotation',
            name='Project',
        ),
        migrations.RemoveField(
            model_name='project_text_annotation',
            name='text_annotation',
        ),
        migrations.RemoveField(
            model_name='project_transform_file',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project_transform_file',
            name='transform_file',
        ),
        migrations.RemoveField(
            model_name='text_annotation',
            name='image_annotation',
        ),
        migrations.RemoveField(
            model_name='text_annotation',
            name='text_annotation_coordinates',
        ),
        migrations.RemoveField(
            model_name='text_annotation',
            name='transform_file',
        ),
        migrations.RemoveField(
            model_name='transform_file',
            name='archival_source',
        ),
        migrations.RemoveField(
            model_name='transform_file',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='transform_file',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='transform_file',
            name='transform_file_coordinates',
        ),
        migrations.RemoveField(
            model_name='transform_file',
            name='upload_file',
        ),
        migrations.RemoveField(
            model_name='transform_file',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transform_file_tag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='transform_file_tag',
            name='transform_file',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='image_annotations',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='text_annotations',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='transformed_files',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image_annotations',
        ),
        migrations.RemoveField(
            model_name='project',
            name='private',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='project',
            name='text_annotations',
        ),
        migrations.RemoveField(
            model_name='project',
            name='transformed_files',
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='bottom_left',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='bottom_right',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='multi_coords',
            field=models.CharField(blank=True, max_length=6000, null=True),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='top_left',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='top_right',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='date_updated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='project',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.Project'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='title',
            field=models.CharField(max_length=2000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_updated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=2000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='upload_file',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='upload_file',
            name='upload_file_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='upload_file',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Archival_Source',
        ),
        migrations.DeleteModel(
            name='Folder_Image_Annotation',
        ),
        migrations.DeleteModel(
            name='Folder_Tag',
        ),
        migrations.DeleteModel(
            name='Folder_Text_Annotation',
        ),
        migrations.DeleteModel(
            name='Folder_Transform_File',
        ),
        migrations.DeleteModel(
            name='Image_Annotation',
        ),
        migrations.DeleteModel(
            name='Image_Annotation_Tag',
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
        migrations.DeleteModel(
            name='Project_Image_Annotation',
        ),
        migrations.DeleteModel(
            name='Project_Tag',
        ),
        migrations.DeleteModel(
            name='Project_Text_Annotation',
        ),
        migrations.DeleteModel(
            name='Project_Transform_File',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='Text_Annotation',
        ),
        migrations.DeleteModel(
            name='Transform_File',
        ),
        migrations.DeleteModel(
            name='Transform_File_Tag',
        ),
        migrations.AddField(
            model_name='text_file',
            name='text_file_coordinates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.Coordinates'),
        ),
        migrations.AddField(
            model_name='image_file_tag',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_file_tag', to='image_lucida_app.Tag'),
        ),
        migrations.AddField(
            model_name='image_file',
            name='image_file_coordinates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.Coordinates'),
        ),
        migrations.AddField(
            model_name='image_file',
            name='tags',
            field=models.ManyToManyField(through='image_lucida_app.Image_File_Tag', to='image_lucida_app.Tag'),
        ),
        migrations.AddField(
            model_name='group',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.Source'),
        ),
        migrations.AddField(
            model_name='file_tag',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_tag', to='image_lucida_app.Tag'),
        ),
        migrations.AddField(
            model_name='file',
            name='file_coordinates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.Coordinates'),
        ),
        migrations.AddField(
            model_name='file',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.Group'),
        ),
        migrations.AddField(
            model_name='file',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.Source'),
        ),
        migrations.AddField(
            model_name='file',
            name='tags',
            field=models.ManyToManyField(through='image_lucida_app.File_Tag', to='image_lucida_app.Tag'),
        ),
        migrations.AddField(
            model_name='file',
            name='upload_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.Upload_File'),
        ),
        migrations.AddField(
            model_name='bucket',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.Folder'),
        ),
    ]
