# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0039_auto_20171229_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text_file',
            name='text_file_coordinates',
        ),
        migrations.AlterField(
            model_name='file',
            name='file_item',
            field=models.ImageField(upload_to='files/'),
        ),
    ]
