# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0040_auto_20180110_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_item',
            field=models.ImageField(max_length=2000, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='image_file',
            name='image_file',
            field=models.ImageField(max_length=2000, null=True, upload_to='image-files/'),
        ),
    ]
