# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0041_auto_20180110_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='bucket_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
