# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 02:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0042_auto_20180118_0211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucket',
            old_name='bucket_type',
            new_name='description',
        ),
    ]
