# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0043_auto_20180118_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='publication_location',
            new_name='description',
        ),
    ]
