# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0044_auto_20180118_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_file',
            name='image_order',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
