# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0045_image_file_image_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='bucket_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='title',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
