# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-28 02:57
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import image_lucida_app.helpers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image_lucida_app', '0046_auto_20180123_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_file_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('base_file', models.ImageField(max_length=2000, upload_to=image_lucida_app.helpers.UniqueFileName('files/'))),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('transformed', models.BooleanField(default=False)),
                ('assigned', models.BooleanField(default=False)),
                ('height', models.IntegerField(default=0, null=True)),
                ('width', models.IntegerField(default=0, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('tesseract_processed', models.BooleanField(default=False)),
                ('google_vision_processed', models.BooleanField(default=False)),
                ('auto_image_processed', models.BooleanField(default=False)),
                ('manual_image_processed', models.BooleanField(default=False)),
                ('base_file_coordinates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.Coordinates')),
                ('transformed_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_transformed_file', to='image_lucida_app.Base_File')),
                ('upload_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_upload_file', to='image_lucida_app.Base_File')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='upload_file',
            name='upload_file_coordinates',
        ),
        migrations.RemoveField(
            model_name='upload_file',
            name='user',
        ),
        migrations.RemoveField(
            model_name='file',
            name='assigned',
        ),
        migrations.RemoveField(
            model_name='file',
            name='auto_image_processed',
        ),
        migrations.RemoveField(
            model_name='file',
            name='file_coordinates',
        ),
        migrations.RemoveField(
            model_name='file',
            name='file_item',
        ),
        migrations.RemoveField(
            model_name='file',
            name='google_vision_processed',
        ),
        migrations.RemoveField(
            model_name='file',
            name='height',
        ),
        migrations.RemoveField(
            model_name='file',
            name='manual_image_processed',
        ),
        migrations.RemoveField(
            model_name='file',
            name='tesseract_processed',
        ),
        migrations.RemoveField(
            model_name='file',
            name='upload_file',
        ),
        migrations.RemoveField(
            model_name='file',
            name='width',
        ),
        migrations.RemoveField(
            model_name='image_file',
            name='google_vision_processed',
        ),
        migrations.RemoveField(
            model_name='image_file',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='image_file',
            name='image_file_coordinates',
        ),
        migrations.RemoveField(
            model_name='image_file',
            name='tesseract_processed',
        ),
        migrations.RemoveField(
            model_name='text_file',
            name='file_item',
        ),
        migrations.RemoveField(
            model_name='text_file',
            name='image_file',
        ),
        migrations.AddField(
            model_name='text_file',
            name='google_vision_document_response',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='Upload_File',
        ),
        migrations.AddField(
            model_name='file',
            name='base_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.Base_File'),
        ),
        migrations.AddField(
            model_name='image_file',
            name='base_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.Base_File'),
        ),
        migrations.AddField(
            model_name='text_file',
            name='base_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.Base_File'),
        ),
    ]
