# Generated by Django 2.0.3 on 2018-03-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0047_auto_20180128_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_file',
            name='base_file',
            field=models.ImageField(max_length=2000, upload_to='files/'),
        ),
    ]
