# Generated by Django 2.0.3 on 2018-03-28 18:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0048_auto_20180328_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='text_file',
            name='google_translate_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='text_file',
            name='google_translate_text_response',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
