# Generated by Django 2.0.3 on 2018-05-25 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image_lucida_app', '0049_auto_20180328_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('image_file_name', models.CharField(blank=True, max_length=2000, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('image_order', models.IntegerField(default=0, null=True)),
                ('contains_image', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='File_Tag',
            new_name='FileTag',
        ),
        migrations.RenameModel(
            old_name='Text_File',
            new_name='TextFile',
        ),
        migrations.RemoveField(
            model_name='image_file',
            name='base_file',
        ),
        migrations.RemoveField(
            model_name='image_file',
            name='file_item',
        ),
        migrations.RemoveField(
            model_name='image_file',
            name='tags',
        ),
        migrations.AlterField(
            model_name='image_file_tag',
            name='image_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_file_tag', to='image_lucida_app.ImageFile'),
        ),
        migrations.RenameModel(
            old_name='Base_File',
            new_name='BaseFile',
        ),
        migrations.DeleteModel(
            name='Image_File',
        ),
        migrations.AddField(
            model_name='imagefile',
            name='base_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.BaseFile'),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='file_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_lucida_app.File'),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='tags',
            field=models.ManyToManyField(through='image_lucida_app.Image_File_Tag', to='image_lucida_app.Tag'),
        ),
    ]
