# Generated by Django 2.0.3 on 2018-06-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0050_auto_20180525_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='contains_image',
            field=models.BooleanField(default=False),
        ),
    ]
