# Generated by Django 2.2.7 on 2021-04-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_lucida_app', '0052_auto_20190321_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textfile',
            old_name='google_vision_document_response',
            new_name='google_documentai_response',
        ),
        migrations.AddField(
            model_name='textfile',
            name='google_documentai_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
